name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build bookmarklet
        run: npm run build
      
      - name: Build loader bookmarklet
        run: npm run build:loader
      
      - name: Get loader code for release
        id: loader
        run: |
          LOADER_CODE=$(node scripts/get-loader-for-release.js)
          echo "code<<EOF" >> $GITHUB_OUTPUT
          echo "$LOADER_CODE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/bookmarklet.min.js
            dist/bookmarklet-loader.min.js
          generate_release_notes: true
          body: |
            ## Installation
            
            Create a new bookmark in your browser with this code:
            ```javascript
            ${{ steps.loader.outputs.code }}
            ```
            
            ## Usage
            1. Navigate to your Amazon Synchrony Store Card activity page
            2. Click the bookmark
            3. Follow the prompts to sync with YNAB
            
            ## What's Changed
            See below for full changelog.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}