name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build bookmarklet
        run: npm run build
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/bookmarklet.min.js
          generate_release_notes: true
          body: |
            ## Installation
            
            Create a new bookmark in your browser with this code:
            ```javascript
            javascript:(function(){const e="${{ github.repository_owner }}",t="${{ github.event.repository.name }}",o=document.createElement("div");o.style.cssText="position:fixed;top:20px;right:20px;padding:10px 20px;background:#007bff;color:white;border-radius:4px;font-family:Arial,sans-serif;z-index:10000;box-shadow:0 2px 4px rgba(0,0,0,0.2)",o.textContent="Loading YNAB Sync Bookmarklet...",document.body.appendChild(o),fetch(`https://api.github.com/repos/${e}/${t}/releases/latest`).then(e=>e.json()).then(e=>{const t=e.assets.find(e=>"bookmarklet.min.js"===e.name);if(!t)throw new Error("Bookmarklet file not found in latest release");const n=document.createElement("script");n.src=t.browser_download_url,n.onload=()=>{document.body.removeChild(o),document.head.removeChild(n)},n.onerror=()=>{document.body.removeChild(o),document.head.removeChild(n),alert("Failed to load bookmarklet script")},document.head.appendChild(n)}).catch(e=>{document.body.contains(o)&&document.body.removeChild(o),alert(`Failed to load YNAB bookmarklet: ${e.message}\n\nMake sure you're on the Amazon Synchrony activity page.`),console.error("Bookmarklet loading error:",e)})})()
            ```
            
            ## Usage
            1. Navigate to your Amazon Synchrony Store Card activity page
            2. Click the bookmark
            3. Follow the prompts to sync with YNAB
            
            ## What's Changed
            See below for full changelog.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}